### ISSUE TITLE
Erro no sistema de bolsa de valores

### ISSUE THREAD

**Issue by VenusKaffee** [NextPlugins/NextEconomy#21]
![image](https://user-images.githubusercontent.com/80410080/135737098-c2886e26-8d38-42ec-8ad4-949ce0a8a61f.png)

**Comment by uRyanxD** [comment]
Yuhtin queria algo pra fazer agora tem K

**Comment by Yuhtin** [comment]
@VenusKaffee Qual a versão do NextEconomy que está usando?

**Comment by VenusKaffee** [comment]
> @VenusKaffee Qual a versão do NextEconomy que está usando?
> 
> Aparentemente é apenas erro de configuração, se tiver algum erro do console seria melhor de ver qual é o valor que está errado/faltando

Atualizei o plugin pra versão mais recente no dia anterior, mas irei conferir o console assim como dito.

**Comment by VenusKaffee** [comment]
@Yuhtin 
[01:05:13 INFO]: VenusCoffee issued server command: /2 buy


[01:05:13 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "com.nextplugins.economy.configuration.PurseValue.get(java.util.function.Function)" is null


[01:05:13 WARN]: 	at NextEconomy-2.0.3.jar//com.nextplugins.economy.api.model.account.Account.createTransaction(Account.java:168)


[01:05:13 WARN]: 	at NextEconomy-2.0.3.jar//com.nextplugins.economy.vault.VaultEconomyHook.withdrawPlayer(VaultEconomyHook.java:89)


[01:05:13 WARN]: 	at PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar//com.plotsquared.bukkit.util.BukkitEconHandler.withdrawMoney(BukkitEconHandler.java:80)


[01:05:13 WARN]: 	at PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar//com.plotsquared.core.command.Buy.execute(Buy.java:110)


[01:05:13 WARN]: 	at PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar//com.plotsquared.core.command.Command.execute(Command.java:365)


[01:05:13 WARN]: 	at PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar//com.plotsquared.core.command.MainCommand.execute(MainCommand.java:312)


[01:05:13 WARN]: 	at PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar//com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:187)


[01:05:13 WARN]: 	at PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar//com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:54)


[01:05:13 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)


[01:05:13 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)


[01:05:13 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:841)


[01:05:13 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257)


[01:05:13 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2068)


[01:05:13 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2049)


[01:05:13 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)


[01:05:13 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)


[01:05:13 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)


[01:05:13 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)


[01:05:13 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)


[01:05:13 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)


[01:05:13 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)


[01:05:13 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)


[01:05:13 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)


[01:05:13 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by uRyanxD** [comment]
Tenta ativar a bolsa de valores e vê se vai acho que ele não Tá indo por causa da bolsa, se for isso só enchendo o saco do yuhtin pra arrumar

**Comment by Yuhtin** [comment]
Você usava qual versão do nexteconomy?

**Comment by VenusKaffee** [comment]
2.0.0

**Comment by Yuhtin** [comment]
Você precisa apagar a config.yml, inventories.yml, ranking.yml, messages.yml e discord.yml. Todos esses arquivos sofreram alterações desde a 2.0.0 até a 2.0.3

**Comment by VenusKaffee** [comment]
Funcionando corretamente, muito obrigado!
