### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by terracraftofc** [NextPlugins/NextEconomy#44]
The following error appears when starting the server:

[05:33:22 INFO]: [com.nextplugins.economy.libs.hikari.HikariDataSource] HikariPool-1 - Starting...
[05:33:23 ERROR]: [com.nextplugins.economy.libs.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.nextplugins.economy.libs.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.sqlprovider.connector.type.RemoteDatabaseType$1.consumeConnection(RemoteDatabaseType.java:40) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.sqlprovider.executor.SQLExecutor.resultQuery(SQLExecutor.java:43) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.sqlprovider.executor.SQLExecutor.resultManyQuery(SQLExecutor.java:79) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.dao.repository.AccountRepository.selectSimpleAll(AccountRepository.java:62) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.listener.events.update.RankingListener.lambda$onRankingUpdate$0(RankingListener.java:57) ~[NextEconomy-2.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-241]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:121) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        ... 21 more
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:121) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809) ~[mysql-connector-j-8.1.0.jar:8.1.0]
        ... 21 more
[05:33:23 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[05:33:23 WARN]:
[05:33:23 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[05:33:23 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.sqlprovider.connector.type.RemoteDatabaseType$1.consumeConnection(RemoteDatabaseType.java:40)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.sqlprovider.executor.SQLExecutor.resultQuery(SQLExecutor.java:43)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.libs.sqlprovider.executor.SQLExecutor.resultManyQuery(SQLExecutor.java:79)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.dao.repository.AccountRepository.selectSimpleAll(AccountRepository.java:62)
[05:33:23 WARN]:        at NextEconomy-2.2.0.jar//com.nextplugins.economy.listener.events.update.RankingListener.lambda$onRankingUpdate$0(RankingListener.java:57)
[05:33:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[05:33:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[05:33:23 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:33:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[05:33:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:33:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[05:33:23 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[05:33:23 WARN]:
[05:33:23 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[05:33:23 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:33:23 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[05:33:23 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:33:23 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[05:33:23 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[05:33:23 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[05:33:23 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[05:33:23 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[05:33:23 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
[05:33:23 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[05:33:23 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:121)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939)
[05:33:23 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809)
[05:33:23 WARN]:        ... 21 more
[05:33:23 WARN]: Caused by: java.net.ConnectException: Connection refused: no further information
[05:33:23 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[05:33:23 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[05:33:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
[05:33:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[05:33:23 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[05:33:23 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[05:33:23 WARN]:        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
[05:33:23 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[05:33:23 WARN]:        ... 24 more
[05:33:23 WARN]: [NextEconomy] Plugin NextEconomy v2.2.0 generated an exception while executing task 369
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
        at java.util.ArrayList.addAll(ArrayList.java:670) ~[?:?]
        at com.nextplugins.economy.listener.events.update.RankingListener.lambda$onRankingUpdate$0(RankingListener.java:57) ~[NextEconomy-2.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-241]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by cjserversofc** [comment]
another error

[05:42:06 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[05:42:06 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_20_R2) is not supported by this NBT-API Version(2.11.3) located in NextEconomy. The NBT-API will try to work as good as it can! Some functions may not work!
[05:42:06 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[05:42:06 ERROR]: Could not pass event PlayerInteractEvent to NextEconomy v2.2.0
com.nextplugins.economy.libs.nbtapi.NbtApiException: [?]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class java.lang.Boolean
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:624) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasKey(NBTCompound.java:611) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.listener.events.check.CheckInteractListener.onCheckInteract(CheckInteractListener.java:36) ~[NextEconomy-2.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor255.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-241]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-241]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1907) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@414fe445
        at jdk.internal.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[NextEconomy-2.2.0.jar:?]
        ... 30 more
[05:42:06 ERROR]: Could not pass event PlayerInteractEvent to NextEconomy v2.2.0
com.nextplugins.economy.libs.nbtapi.NbtApiException: [?]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class java.lang.Boolean
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:624) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasKey(NBTCompound.java:611) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.listener.events.check.CheckInteractListener.onCheckInteract(CheckInteractListener.java:36) ~[NextEconomy-2.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor255.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-241]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-241]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1907) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@68b61d2f
        at jdk.internal.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[NextEconomy-2.2.0.jar:?]
        ... 30 more
[05:42:24 INFO]: [Not Secure] <.Cauajosecunha17> cancelar
[05:43:54 ERROR]: Could not pass event PlayerInteractEvent to NextEconomy v2.2.0
com.nextplugins.economy.libs.nbtapi.NbtApiException: [?]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class java.lang.Boolean
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:624) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasKey(NBTCompound.java:611) ~[NextEconomy-2.2.0.jar:?]
        at com.nextplugins.economy.listener.events.check.CheckInteractListener.onCheckInteract(CheckInteractListener.java:36) ~[NextEconomy-2.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor255.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-241]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-241]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1907) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@47f7d58d
        at jdk.internal.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[NextEconomy-2.2.0.jar:?]
        ... 30 more

**Comment by cjserversofc** [comment]
Percebi que esse erro acontece quando o jogador clica na cama, ou simplesmente dorme...

**Comment by eikefab** [comment]
Erro causado por biblioteca desatualizada. Será corrigido em breve.

**Comment by eikefab** [comment]
Erro corrigido via #49.
