### ISSUE TITLE
1.20.4 Update Libs 

### ISSUE THREAD

**Issue by ShizenXD** [NextPlugins/NextEconomy#47]
[12:20:47 ERROR]: Could not pass event PlayerInteractEvent to NextEconomy v2.2.0
com.nextplugins.economy.libs.nbtapi.NbtApiException: [?]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class java.lang.Boolean
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[NextEconomy.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[NextEconomy.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:624) ~[NextEconomy.jar:?]
        at com.nextplugins.economy.libs.nbtapi.NBTCompound.hasKey(NBTCompound.java:611) ~[NextEconomy.jar:?]
        at com.nextplugins.economy.listener.events.check.CheckInteractListener.onCheckInteract(CheckInteractListener.java:36) ~[NextEconomy.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor684.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-393]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-393]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1936) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1452) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1352) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1330) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-393]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@707baaed
        at jdk.internal.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.nextplugins.economy.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[NextEconomy.jar:?]
        ... 30 more

**Comment by ShizenXD** [comment]
@eikefab Update ?

**Comment by ShizenXD** [comment]
@Yuhtin update?

**Comment by ShizenXD** [comment]
@henrysaantos update ?
